#! python


def build(ctx):

    # Illustrate simple use of run_py_script
    ctx(
        features="run_py_script",
        source="clean_data.py",
        deps=ctx.path_to(ctx, "OUT_DATA", "tweets.pickle"),
        target=ctx.path_to(ctx, "OUT_DATA", "normalised_tweets.pickle"),
        name="prepare_and_normalise_tweets_for_ML",
    )
