#! python


def build(ctx):

    # Illustrate simple use of run_py_script
    ctx(
        features="run_py_script",
        source="get_tweets.py",
        deps=ctx.path_to(ctx, "CREDENTIALS", "credentials.pickle"),
        target=ctx.path_to(ctx, "OUT_DATA", "tweets.pickle"),
        name="get_tweets",
    )
