#! python


def build(ctx):


    ctx(
        features="run_py_script",
        source="secrets.py",
        target=ctx.path_to(ctx, "CREDENTIALS", "credentials.pickle"),
        name="Decrypt Twitter credentials",
    )
