#! python


def build(ctx):
    ctx.recurse("credentials")
    ctx.recurse("get_tweets")
    ctx.recurse("test")
    ctx.recurse("library")
    ctx.recurse("data_management")
    #ctx.recurse("analysis")
    #ctx.recurse("final")

    # Safety measure -- else the LaTeX scanner might fail because some
    # '.tex'-source file has not been generated.
    ctx.add_group()
    #ctx.recurse("paper")
a = 'asdf'
a*8
